version: '3.7'
services:
  redis:
    image: redis:alpine
    command:
      - redis-server
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6375:6379" 
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ['celery', '-A', 'celeryapp', 'worker', '-l', 'info']
    volumes:
      - ./:/app/
    depends_on:
      - redis
  bot:
   build:
     context: .
     dockerfile: Dockerfile
   command: python3 bot.py
   env_file:
    - ./.env
   restart: always
   volumes:
      - ./:/app/
   depends_on:
    - redis

volumes:
  pgdata:
